name: Build repo

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build-repo:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Build repo
                run: |
                    ./repo/scripts/build-repo-in-docker

    build-repo-to-deploy:
        if: ${{ github.ref_name == 'main' }}

        runs-on: ubuntu-latest

        environment:
            name: build-repo-deploy

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Copy signing key
                run: |
                    echo "$GPG_KEY" > ./repo/docker/gpg.key
                    echo "$GPG_PASS" > ./repo/docker/gpg.pass
                env:
                    GPG_KEY: ${{ secrets.APT_REPO_SIGNING_GPG_KEY }}
                    GPG_PASS: ${{ secrets.APT_REPO_SIGNING_GPG_PASS }}

            -   name: Build repo
                run: |
                    ./repo/scripts/build-repo-in-docker

            -   name: Upload Pages artifact
                uses: actions/upload-pages-artifact@v3
                with:
                      path: repo/dest/

    release:
        if: ${{ github.ref_name == 'main' }}

        needs:
            - build-repo-to-deploy

        runs-on: ubuntu-latest

        permissions:
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            -   name: Deploy to GitHub Pages
                id: deployment
                uses: actions/deploy-pages@v4
